name: flutter_android_developer_mode
description: Check if Android device is in Developer Mode.
version: 1.0.0
homepage: https://github.com/jonatanbortolon
repository: https://github.com/jonatanbortolon/flutter-android-developer-mode

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jonatanbortolon.flutter_android_developer_mode
        pluginClass: FlutterAndroidDeveloperModePlugin
